//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CLient.server {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchByDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchBynameOperationCompleted;
        
        private System.Threading.SendOrPostCallback registerStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback registerTeacherOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsValidOperationCompleted;
        
        private System.Threading.SendOrPostCallback resetpaswrdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsValidTeacherOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsValidStuOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchBySectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback showallOperationCompleted;
        
        private System.Threading.SendOrPostCallback registerSubjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback unregisterSubjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSubjectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback loggedInStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback loggedInStudentSubjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback showResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback BySectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::CLient.Properties.Settings.Default.CLient_server_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchByDepartmentCompletedEventHandler SearchByDepartmentCompleted;
        
        /// <remarks/>
        public event SearchBynameCompletedEventHandler SearchBynameCompleted;
        
        /// <remarks/>
        public event registerStudentCompletedEventHandler registerStudentCompleted;
        
        /// <remarks/>
        public event registerTeacherCompletedEventHandler registerTeacherCompleted;
        
        /// <remarks/>
        public event IsValidCompletedEventHandler IsValidCompleted;
        
        /// <remarks/>
        public event resetpaswrdCompletedEventHandler resetpaswrdCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event IsValidTeacherCompletedEventHandler IsValidTeacherCompleted;
        
        /// <remarks/>
        public event IsValidStuCompletedEventHandler IsValidStuCompleted;
        
        /// <remarks/>
        public event SearchByNameCompletedEventHandler SearchByNameCompleted;
        
        /// <remarks/>
        public event SearchBySectionCompletedEventHandler SearchBySectionCompleted;
        
        /// <remarks/>
        public event ShowAllCompletedEventHandler ShowAllCompleted;
        
        /// <remarks/>
        public event showallCompletedEventHandler showallCompleted;
        
        /// <remarks/>
        public event registerSubjectCompletedEventHandler registerSubjectCompleted;
        
        /// <remarks/>
        public event unregisterSubjectCompletedEventHandler unregisterSubjectCompleted;
        
        /// <remarks/>
        public event getSubjectsCompletedEventHandler getSubjectsCompleted;
        
        /// <remarks/>
        public event loggedInStudentCompletedEventHandler loggedInStudentCompleted;
        
        /// <remarks/>
        public event loggedInStudentSubjectCompletedEventHandler loggedInStudentSubjectCompleted;
        
        /// <remarks/>
        public event AddResultCompletedEventHandler AddResultCompleted;
        
        /// <remarks/>
        public event showResultCompletedEventHandler showResultCompleted;
        
        /// <remarks/>
        public event BySectionCompletedEventHandler BySectionCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SearchByDepartment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        public Teacher[] SearchByDepartment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Department) {
            object[] results = this.Invoke("SearchByDepartment", new object[] {
                        Department});
            return ((Teacher[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchByDepartmentAsync(string Department) {
            this.SearchByDepartmentAsync(Department, null);
        }
        
        /// <remarks/>
        public void SearchByDepartmentAsync(string Department, object userState) {
            if ((this.SearchByDepartmentOperationCompleted == null)) {
                this.SearchByDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByDepartmentOperationCompleted);
            }
            this.InvokeAsync("SearchByDepartment", new object[] {
                        Department}, this.SearchByDepartmentOperationCompleted, userState);
        }
        
        private void OnSearchByDepartmentOperationCompleted(object arg) {
            if ((this.SearchByDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByDepartmentCompleted(this, new SearchByDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SearchByname", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        public Teacher[] SearchByname([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Name) {
            object[] results = this.Invoke("SearchByname", new object[] {
                        Name});
            return ((Teacher[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchBynameAsync(string Name) {
            this.SearchBynameAsync(Name, null);
        }
        
        /// <remarks/>
        public void SearchBynameAsync(string Name, object userState) {
            if ((this.SearchBynameOperationCompleted == null)) {
                this.SearchBynameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchBynameOperationCompleted);
            }
            this.InvokeAsync("SearchByname", new object[] {
                        Name}, this.SearchBynameOperationCompleted, userState);
        }
        
        private void OnSearchBynameOperationCompleted(object arg) {
            if ((this.SearchBynameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchBynameCompleted(this, new SearchBynameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/registerStudent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registerStudent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pincode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string section) {
            this.Invoke("registerStudent", new object[] {
                        username,
                        password,
                        email,
                        pincode,
                        section});
        }
        
        /// <remarks/>
        public void registerStudentAsync(string username, string password, string email, string pincode, string section) {
            this.registerStudentAsync(username, password, email, pincode, section, null);
        }
        
        /// <remarks/>
        public void registerStudentAsync(string username, string password, string email, string pincode, string section, object userState) {
            if ((this.registerStudentOperationCompleted == null)) {
                this.registerStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterStudentOperationCompleted);
            }
            this.InvokeAsync("registerStudent", new object[] {
                        username,
                        password,
                        email,
                        pincode,
                        section}, this.registerStudentOperationCompleted, userState);
        }
        
        private void OnregisterStudentOperationCompleted(object arg) {
            if ((this.registerStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerStudentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/registerTeacher", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registerTeacher([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pincode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string subject, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string department) {
            this.Invoke("registerTeacher", new object[] {
                        username,
                        password,
                        email,
                        pincode,
                        subject,
                        department});
        }
        
        /// <remarks/>
        public void registerTeacherAsync(string username, string password, string email, string pincode, string subject, string department) {
            this.registerTeacherAsync(username, password, email, pincode, subject, department, null);
        }
        
        /// <remarks/>
        public void registerTeacherAsync(string username, string password, string email, string pincode, string subject, string department, object userState) {
            if ((this.registerTeacherOperationCompleted == null)) {
                this.registerTeacherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterTeacherOperationCompleted);
            }
            this.InvokeAsync("registerTeacher", new object[] {
                        username,
                        password,
                        email,
                        pincode,
                        subject,
                        department}, this.registerTeacherOperationCompleted, userState);
        }
        
        private void OnregisterTeacherOperationCompleted(object arg) {
            if ((this.registerTeacherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerTeacherCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/IsValid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IsValid([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool IsValidResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IsValidResultSpecified) {
            object[] results = this.Invoke("IsValid", new object[] {
                        username,
                        password});
            IsValidResult = ((bool)(results[0]));
            IsValidResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void IsValidAsync(string username, string password) {
            this.IsValidAsync(username, password, null);
        }
        
        /// <remarks/>
        public void IsValidAsync(string username, string password, object userState) {
            if ((this.IsValidOperationCompleted == null)) {
                this.IsValidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsValidOperationCompleted);
            }
            this.InvokeAsync("IsValid", new object[] {
                        username,
                        password}, this.IsValidOperationCompleted, userState);
        }
        
        private void OnIsValidOperationCompleted(object arg) {
            if ((this.IsValidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsValidCompleted(this, new IsValidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/resetpaswrd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void resetpaswrd([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pin, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string user, out bool resetpaswrdResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool resetpaswrdResultSpecified) {
            object[] results = this.Invoke("resetpaswrd", new object[] {
                        name,
                        pin,
                        user});
            resetpaswrdResult = ((bool)(results[0]));
            resetpaswrdResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void resetpaswrdAsync(string name, string pin, string user) {
            this.resetpaswrdAsync(name, pin, user, null);
        }
        
        /// <remarks/>
        public void resetpaswrdAsync(string name, string pin, string user, object userState) {
            if ((this.resetpaswrdOperationCompleted == null)) {
                this.resetpaswrdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresetpaswrdOperationCompleted);
            }
            this.InvokeAsync("resetpaswrd", new object[] {
                        name,
                        pin,
                        user}, this.resetpaswrdOperationCompleted, userState);
        }
        
        private void OnresetpaswrdOperationCompleted(object arg) {
            if ((this.resetpaswrdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.resetpaswrdCompleted(this, new resetpaswrdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/IsValidTeacher", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IsValidTeacher([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool IsValidTeacherResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IsValidTeacherResultSpecified) {
            object[] results = this.Invoke("IsValidTeacher", new object[] {
                        username,
                        password});
            IsValidTeacherResult = ((bool)(results[0]));
            IsValidTeacherResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void IsValidTeacherAsync(string username, string password) {
            this.IsValidTeacherAsync(username, password, null);
        }
        
        /// <remarks/>
        public void IsValidTeacherAsync(string username, string password, object userState) {
            if ((this.IsValidTeacherOperationCompleted == null)) {
                this.IsValidTeacherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsValidTeacherOperationCompleted);
            }
            this.InvokeAsync("IsValidTeacher", new object[] {
                        username,
                        password}, this.IsValidTeacherOperationCompleted, userState);
        }
        
        private void OnIsValidTeacherOperationCompleted(object arg) {
            if ((this.IsValidTeacherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsValidTeacherCompleted(this, new IsValidTeacherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/IsValidStu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IsValidStu([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool IsValidStuResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IsValidStuResultSpecified) {
            object[] results = this.Invoke("IsValidStu", new object[] {
                        username,
                        password});
            IsValidStuResult = ((bool)(results[0]));
            IsValidStuResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void IsValidStuAsync(string username, string password) {
            this.IsValidStuAsync(username, password, null);
        }
        
        /// <remarks/>
        public void IsValidStuAsync(string username, string password, object userState) {
            if ((this.IsValidStuOperationCompleted == null)) {
                this.IsValidStuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsValidStuOperationCompleted);
            }
            this.InvokeAsync("IsValidStu", new object[] {
                        username,
                        password}, this.IsValidStuOperationCompleted, userState);
        }
        
        private void OnIsValidStuOperationCompleted(object arg) {
            if ((this.IsValidStuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsValidStuCompleted(this, new IsValidStuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SearchByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        public Student[] SearchByName([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string UserName) {
            object[] results = this.Invoke("SearchByName", new object[] {
                        UserName});
            return ((Student[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchByNameAsync(string UserName) {
            this.SearchByNameAsync(UserName, null);
        }
        
        /// <remarks/>
        public void SearchByNameAsync(string UserName, object userState) {
            if ((this.SearchByNameOperationCompleted == null)) {
                this.SearchByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByNameOperationCompleted);
            }
            this.InvokeAsync("SearchByName", new object[] {
                        UserName}, this.SearchByNameOperationCompleted, userState);
        }
        
        private void OnSearchByNameOperationCompleted(object arg) {
            if ((this.SearchByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByNameCompleted(this, new SearchByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SearchBySection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        public Student[] SearchBySection([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string section) {
            object[] results = this.Invoke("SearchBySection", new object[] {
                        section});
            return ((Student[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchBySectionAsync(string section) {
            this.SearchBySectionAsync(section, null);
        }
        
        /// <remarks/>
        public void SearchBySectionAsync(string section, object userState) {
            if ((this.SearchBySectionOperationCompleted == null)) {
                this.SearchBySectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchBySectionOperationCompleted);
            }
            this.InvokeAsync("SearchBySection", new object[] {
                        section}, this.SearchBySectionOperationCompleted, userState);
        }
        
        private void OnSearchBySectionOperationCompleted(object arg) {
            if ((this.SearchBySectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchBySectionCompleted(this, new SearchBySectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ShowAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        public Student[] ShowAll() {
            object[] results = this.Invoke("ShowAll", new object[0]);
            return ((Student[])(results[0]));
        }
        
        /// <remarks/>
        public void ShowAllAsync() {
            this.ShowAllAsync(null);
        }
        
        /// <remarks/>
        public void ShowAllAsync(object userState) {
            if ((this.ShowAllOperationCompleted == null)) {
                this.ShowAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowAllOperationCompleted);
            }
            this.InvokeAsync("ShowAll", new object[0], this.ShowAllOperationCompleted, userState);
        }
        
        private void OnShowAllOperationCompleted(object arg) {
            if ((this.ShowAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowAllCompleted(this, new ShowAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/showall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        public Teacher[] showall() {
            object[] results = this.Invoke("showall", new object[0]);
            return ((Teacher[])(results[0]));
        }
        
        /// <remarks/>
        public void showallAsync() {
            this.showallAsync(null);
        }
        
        /// <remarks/>
        public void showallAsync(object userState) {
            if ((this.showallOperationCompleted == null)) {
                this.showallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowallOperationCompleted);
            }
            this.InvokeAsync("showall", new object[0], this.showallOperationCompleted, userState);
        }
        
        private void OnshowallOperationCompleted(object arg) {
            if ((this.showallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showallCompleted(this, new showallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/registerSubject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registerSubject([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Student student, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Subject subject) {
            this.Invoke("registerSubject", new object[] {
                        student,
                        subject});
        }
        
        /// <remarks/>
        public void registerSubjectAsync(Student student, Subject subject) {
            this.registerSubjectAsync(student, subject, null);
        }
        
        /// <remarks/>
        public void registerSubjectAsync(Student student, Subject subject, object userState) {
            if ((this.registerSubjectOperationCompleted == null)) {
                this.registerSubjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterSubjectOperationCompleted);
            }
            this.InvokeAsync("registerSubject", new object[] {
                        student,
                        subject}, this.registerSubjectOperationCompleted, userState);
        }
        
        private void OnregisterSubjectOperationCompleted(object arg) {
            if ((this.registerSubjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerSubjectCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/unregisterSubject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void unregisterSubject([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Student student, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Subject subject) {
            this.Invoke("unregisterSubject", new object[] {
                        student,
                        subject});
        }
        
        /// <remarks/>
        public void unregisterSubjectAsync(Student student, Subject subject) {
            this.unregisterSubjectAsync(student, subject, null);
        }
        
        /// <remarks/>
        public void unregisterSubjectAsync(Student student, Subject subject, object userState) {
            if ((this.unregisterSubjectOperationCompleted == null)) {
                this.unregisterSubjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunregisterSubjectOperationCompleted);
            }
            this.InvokeAsync("unregisterSubject", new object[] {
                        student,
                        subject}, this.unregisterSubjectOperationCompleted, userState);
        }
        
        private void OnunregisterSubjectOperationCompleted(object arg) {
            if ((this.unregisterSubjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unregisterSubjectCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/getSubjects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        public Subject[] getSubjects() {
            object[] results = this.Invoke("getSubjects", new object[0]);
            return ((Subject[])(results[0]));
        }
        
        /// <remarks/>
        public void getSubjectsAsync() {
            this.getSubjectsAsync(null);
        }
        
        /// <remarks/>
        public void getSubjectsAsync(object userState) {
            if ((this.getSubjectsOperationCompleted == null)) {
                this.getSubjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSubjectsOperationCompleted);
            }
            this.InvokeAsync("getSubjects", new object[0], this.getSubjectsOperationCompleted, userState);
        }
        
        private void OngetSubjectsOperationCompleted(object arg) {
            if ((this.getSubjectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSubjectsCompleted(this, new getSubjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/loggedInStudent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Student loggedInStudent() {
            object[] results = this.Invoke("loggedInStudent", new object[0]);
            return ((Student)(results[0]));
        }
        
        /// <remarks/>
        public void loggedInStudentAsync() {
            this.loggedInStudentAsync(null);
        }
        
        /// <remarks/>
        public void loggedInStudentAsync(object userState) {
            if ((this.loggedInStudentOperationCompleted == null)) {
                this.loggedInStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloggedInStudentOperationCompleted);
            }
            this.InvokeAsync("loggedInStudent", new object[0], this.loggedInStudentOperationCompleted, userState);
        }
        
        private void OnloggedInStudentOperationCompleted(object arg) {
            if ((this.loggedInStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loggedInStudentCompleted(this, new loggedInStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/loggedInStudentSubject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        public Subject[] loggedInStudentSubject() {
            object[] results = this.Invoke("loggedInStudentSubject", new object[0]);
            return ((Subject[])(results[0]));
        }
        
        /// <remarks/>
        public void loggedInStudentSubjectAsync() {
            this.loggedInStudentSubjectAsync(null);
        }
        
        /// <remarks/>
        public void loggedInStudentSubjectAsync(object userState) {
            if ((this.loggedInStudentSubjectOperationCompleted == null)) {
                this.loggedInStudentSubjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloggedInStudentSubjectOperationCompleted);
            }
            this.InvokeAsync("loggedInStudentSubject", new object[0], this.loggedInStudentSubjectOperationCompleted, userState);
        }
        
        private void OnloggedInStudentSubjectOperationCompleted(object arg) {
            if ((this.loggedInStudentSubjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loggedInStudentSubjectCompleted(this, new loggedInStudentSubjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AddResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddResult([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string section, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string marksobtained, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string totalmarks, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string status) {
            this.Invoke("AddResult", new object[] {
                        name,
                        section,
                        marksobtained,
                        totalmarks,
                        status});
        }
        
        /// <remarks/>
        public void AddResultAsync(string name, string section, string marksobtained, string totalmarks, string status) {
            this.AddResultAsync(name, section, marksobtained, totalmarks, status, null);
        }
        
        /// <remarks/>
        public void AddResultAsync(string name, string section, string marksobtained, string totalmarks, string status, object userState) {
            if ((this.AddResultOperationCompleted == null)) {
                this.AddResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddResultOperationCompleted);
            }
            this.InvokeAsync("AddResult", new object[] {
                        name,
                        section,
                        marksobtained,
                        totalmarks,
                        status}, this.AddResultOperationCompleted, userState);
        }
        
        private void OnAddResultOperationCompleted(object arg) {
            if ((this.AddResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddResultCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/showResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        public AddallResult[] showResult() {
            object[] results = this.Invoke("showResult", new object[0]);
            return ((AddallResult[])(results[0]));
        }
        
        /// <remarks/>
        public void showResultAsync() {
            this.showResultAsync(null);
        }
        
        /// <remarks/>
        public void showResultAsync(object userState) {
            if ((this.showResultOperationCompleted == null)) {
                this.showResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowResultOperationCompleted);
            }
            this.InvokeAsync("showResult", new object[0], this.showResultOperationCompleted, userState);
        }
        
        private void OnshowResultOperationCompleted(object arg) {
            if ((this.showResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showResultCompleted(this, new showResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/BySection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
        public AddallResult[] BySection([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string section) {
            object[] results = this.Invoke("BySection", new object[] {
                        section});
            return ((AddallResult[])(results[0]));
        }
        
        /// <remarks/>
        public void BySectionAsync(string section) {
            this.BySectionAsync(section, null);
        }
        
        /// <remarks/>
        public void BySectionAsync(string section, object userState) {
            if ((this.BySectionOperationCompleted == null)) {
                this.BySectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBySectionOperationCompleted);
            }
            this.InvokeAsync("BySection", new object[] {
                        section}, this.BySectionOperationCompleted, userState);
        }
        
        private void OnBySectionOperationCompleted(object arg) {
            if ((this.BySectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BySectionCompleted(this, new BySectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    public partial class Teacher {
        
        private string departmentField;
        
        private string emailField;
        
        private string nameField;
        
        private string passwordField;
        
        private string pincodeField;
        
        private string subjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pincode {
            get {
                return this.pincodeField;
            }
            set {
                this.pincodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    public partial class AddallResult {
        
        private string markobtainedField;
        
        private string nameField;
        
        private string sectionField;
        
        private string statusField;
        
        private string totalmarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Markobtained {
            get {
                return this.markobtainedField;
            }
            set {
                this.markobtainedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Totalmarks {
            get {
                return this.totalmarksField;
            }
            set {
                this.totalmarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    public partial class Subject {
        
        private string nameField;
        
        private string teacherField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string teacher {
            get {
                return this.teacherField;
            }
            set {
                this.teacherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    public partial class Student {
        
        private string emailField;
        
        private string nameField;
        
        private string passwordField;
        
        private string pincodeField;
        
        private string sectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Pincode {
            get {
                return this.pincodeField;
            }
            set {
                this.pincodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SearchByDepartmentCompletedEventHandler(object sender, SearchByDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Teacher[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Teacher[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SearchBynameCompletedEventHandler(object sender, SearchBynameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchBynameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchBynameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Teacher[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Teacher[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void registerStudentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void registerTeacherCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void IsValidCompletedEventHandler(object sender, IsValidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsValidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsValidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool IsValidResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool IsValidResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void resetpaswrdCompletedEventHandler(object sender, resetpaswrdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resetpaswrdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal resetpaswrdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool resetpaswrdResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool resetpaswrdResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void IsValidTeacherCompletedEventHandler(object sender, IsValidTeacherCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsValidTeacherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsValidTeacherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool IsValidTeacherResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool IsValidTeacherResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void IsValidStuCompletedEventHandler(object sender, IsValidStuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsValidStuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsValidStuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool IsValidStuResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool IsValidStuResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SearchByNameCompletedEventHandler(object sender, SearchByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Student[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Student[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SearchBySectionCompletedEventHandler(object sender, SearchBySectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchBySectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchBySectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Student[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Student[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ShowAllCompletedEventHandler(object sender, ShowAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Student[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Student[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void showallCompletedEventHandler(object sender, showallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Teacher[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Teacher[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void registerSubjectCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void unregisterSubjectCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getSubjectsCompletedEventHandler(object sender, getSubjectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSubjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSubjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Subject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Subject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void loggedInStudentCompletedEventHandler(object sender, loggedInStudentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loggedInStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loggedInStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Student Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Student)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void loggedInStudentSubjectCompletedEventHandler(object sender, loggedInStudentSubjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loggedInStudentSubjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loggedInStudentSubjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Subject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Subject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AddResultCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void showResultCompletedEventHandler(object sender, showResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddallResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddallResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void BySectionCompletedEventHandler(object sender, BySectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BySectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BySectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddallResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddallResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591